### ISSUE TITLE
Can't instantiate a beam object from an area 

### ISSUE THREAD

**Issue by smaret** [radio-astro-tools/radio-beam#90]
Creating a beam from an area fails with the following error:

```py
from radio_beam import Beam
from astropy import units as u

a = (1 * u.arcsec)**2
b = Beam(area=a)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/radio_beam/beam.py", line 100, in __new__
    self = super(Beam, cls).__new__(cls, _to_area(major,minor).value, u.sr)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/radio_beam/beam.py", line 24, in _to_area
    return (major * minor * FWHM_TO_AREA).to(u.sr)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/quantity.py", line 689, in to
    return self._new_view(self._to_value(unit, equivalencies), unit)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/quantity.py", line 660, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 987, in to
    return self._get_converter(other, equivalencies=equivalencies)(value)
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 918, in _get_converter
    raise exc
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 903, in _get_converter
    return self._apply_equivalencies(
  File "/nix/store/svi6i5417p8y1nz61nr2170a9ys97f74-python3-3.8.6-env/lib/python3.8/site-packages/astropy/units/core.py", line 886, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'arcsec2 deg4' and 'sr' (solid angle) are not convertible
```

I'm using radio_beam 0.3.2.

**Comment by keflavich** [comment]
Indeed, a beam should not be instantiable from an area.  We could potentially create a `CircularBeam` class that could be created from an area, but for a general asymmetric beam, that shouldn't be allowed.

**Comment by smaret** [comment]
I'm confused. Here is the docstring:

```
        area : :class:`~astropy.units.Quantity` with steradian equivalency
            The area of the beam.  This is an alternative to specifying the
            major/minor/PA, and will create those values assuming a circular
            Gaussian beam.
```

**Comment by keflavich** [comment]
:facepalm: you're right.
